apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  labels:
    app: flink-jobmanager
spec:
  selector:
    matchLabels:
      app: flink-jobmanager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1%
  replicas: 2
  template:
    metadata:
      labels:
        app: flink-jobmanager
    spec:
      containers:
        - name: flink-jobmanager
          image: seemscloud/flink:1.0.2
          imagePullPolicy: IfNotPresent
          command: [ "jobmanager.sh" ]
          args: [ "start-foreground" ]
          ports:
            - name: rpc
              containerPort: 6123
            - name: ui
              containerPort: 8080
            - name: blob
              containerPort: 6124
          volumeMounts:
            - mountPath: /app/conf/flink-conf.yaml
              name: flink-config
              subPath: flink-conf.yaml
          readinessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 15
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: flink-config
          configMap:
            name: flink-jobmanager-config