apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: "flink-jobmanager"
        static_configs:
          - targets: ["flink-jobmanager:9090"]