apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  labels:
    app: prometheus
rules:
  - apiGroups: [""]
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: prometheus
  labels:
    app: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
roleRef:
  kind: Role
  name: prometheus
  apiGroup: rbac.authorization.k8s.io