apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  serviceAccountName: prometheus
  automountServiceAccountToken: true
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

#  curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
#  chmod +x ./kubectl
#  mv ./kubectl /usr/local/bin/kubectl
#  kubectl version --client